---
#
# Install/run graphite-web for satellite
#

# - name: Import EPEL GPG Key
#   rpm_key: key=https://dl.fedoraproject.org/pub/epel/RPM-GPG-KEY-EPEL-7 state=present

# - name: Check for EPEL
#   shell: rpm -qa | grep -q epel-release
#   ignore_errors: true
#   register: epel_installed

# - name: Check for EPEL repo
#   yum: name={{ epel_release_rpm }}
#     state=present
#   register: epel_installed

- stat: path=/etc/yum.repos.d/epel.repo
  register: epel_installed

- name: Enable EPEL Repo
  ini_file: dest=/etc/yum.repos.d/epel.repo
    section=epel
    option=enabled
    value=1
  when: epel_installed.stat.exists == True
  register: epel_enabled

# - name: Check for enabled epel-release
#   shell: yum repolist | grep -q epel
#   ignore_errors: true
#   register: epel_enabled

# (akrzos) I have found the use of the yum module for installing EPEL on rhel7 to encounter issues,
# thus using rpm to install via ansible. This does display a warning in Ansible output.
#
- name: Install EPEL rpm
  command: rpm -ivh --force {{ epel_release_rpm }}
  become: true
  when: epel_installed.stat.exists == false or epel_enabled.msg != 'OK'

# (akrzos) yum module works at this point due to the fact the EPEL repo now exists.  EPEL rpm is
# installed at this point in time.
# # fails to get following deps:
# - python-twister-core
#   - python-zope-interface
# EPEL for some reason, removed them again. meh!!

# NOTE: Present in rhel-7-server-optional-rpms
## TODO WARNING: INSECURE method
#- name: Graphite prerequisites not in EPEL at the moment
#  yum: name={{ item }} state=present
#  become: true
#  with_items:
#    - ftp://195.220.108.108/linux/centos/7.2.1511/os/x86_64/Packages/python-zope-interface-4.0.5-4.el7.x86_64.rpm
#    - ftp://195.220.108.108/linux/centos/7.2.1511/os/x86_64/Packages/python-twisted-core-12.2.0-4.el7.x86_64.rpm

- name: Install graphite rpms
  yum: name={{ item }} state=present
  become: true
  with_items:
    - graphite-web
    - python-carbon
    - expect

# moved to grafana specific playbook
#    - https://grafanarel.s3.amazonaws.com/builds/grafana-2.6.0-1.x86_64.rpm

- name: Check for graphite.db sqlite
  stat:
    path=/var/lib/graphite-web/graphite.db
  register: graphite_db_installed

- name: Copy setup-graphite-db.exp
  copy:
    src=setup-graphite-db.exp
    dest=/root/setup-graphite-db.exp
    owner=root
    group=root
    mode=0755
  become: true

#TODO: graphite postinstallation settings
# edit /etc/graphite/local_settings.py
# and set ALLOWED_HOSTS = ['*'] or more constrained set if you'd like

- name: Set SECRET_KEY in graphite config
  shell:
    echo "SECRET_KEY = '{{ 999999999|random }}'" >> /etc/graphite-web/local_settings.py

- name: Create initial graphite db
  shell: /root/setup-graphite-db.exp {{ graphite_username }} {{ graphite_password }} && chown apache:apache /var/lib/graphite-web/graphite.db
  become: true
  when: "graphite_db_installed.stat.exists is defined and graphite_db_installed.stat.exists == true"
  register: apache_needs_restart

- name: Setup httpd graphite-web config
  template:
    src=graphite-web.conf.j2
    dest=/etc/httpd/conf.d/graphite-web.conf
    owner=root
    group=root
    mode=0644
  become: true
  register: apache_needs_restart


# Start graphite-web service

- name: Setup httpd service
  service: name=httpd state=started enabled=true
  become: true

# disable firewalld (might need to create specific firewall rules or leave it to admin to do via iptables)

- name: disable firewalld
  service: name=firewalld state=stopped enabled=false
  become: true
  ignore_errors: true

# remove silly welcome from apache (if it exists)
- name: Remove httpd welcome config
  become: true
  file: path=/etc/httpd/conf.d/welcome.conf state=absent
  register: apache_needs_restart

- name: Bounce Apache
  service: name=httpd state=restarted enabled=true
  become: true
  when: apache_needs_restart.changed

#
# setup the python-carbon service
#

- name: Setup carbon-cache service
  service: name=carbon-cache state=started enabled=true
  become: true

- name: copy carbon storage schema config
  copy:
    src=storage-schemas.conf
    dest=/etc/carbon/storage-schemas.conf
    owner=root
    group=root
    mode=0644
  become: true
  register: carbon_cache_needs_restart

- name: copy carbon storage aggregation config
  copy:
    src=storage-aggregation.conf
    dest=/etc/carbon/storage-aggregation.conf
    owner=root
    group=root
    mode=0644
  become: true
  register: carbon_cache_needs_restart

- name: copy carbon config
  copy:
    src=carbon.conf
    dest=/etc/carbon/carbon.conf
    owner=root
    group=root
    mode=0644
  become: true
  register: carbon_cache_needs_restart

# - name: Disable EPEL Repo
#   ini_file: dest=/etc/yum.repos.d/epel.repo
#     section=epel
#     option=enabled
#     value=0

- name: bounce carbon cache
  service: name=carbon-cache state=restarted enabled=true
  become: true
  when: carbon_cache_needs_restart.changed

# sometimes there's a stale epel package present, so rpm -e fails
# because somebody deleted the .repo files without uninstalling
# epel-release and rpm -e fails to remove multiple versions of the
# package. So we need to check this and remove all one by one
- name: Disable EPEL
  shell: |
    count=$(rpm -q epel-release | wc -l)
    if [[ $count -gt 1 ]]; then
      for ver in `rpm -q epel-release`; do
        rpm -e $ver
      done
    else
      rpm -e epel-release
    fi
  ignore_errors: true
  become: true
