---
- hosts: capsules
  remote_user: root
  ###gather_facts: no
  vars_files:
    - ../../conf/satperf.yaml
    - ../../conf/satperf.local.yaml
  roles:
    ###- common-eth1
    - common
    - epel-not-present
    - rhsm-satellite
    - ntp
    ###- upgrade-restart
    ###- capsule-ec2-partitioning
    - ../common/roles/remove-home-extend-root
    - capsule
    - capsule-location
    - enlarge-arp-table
    ###- capsule-myrhev-partitioning
    - capsule-populate
