---
- name: "Configure capsule(s)"
  hosts: capsules
  gather_facts: false

  roles:
    - role: linux-system-roles.firewall
    - role: linux-system-roles.storage
    - role: ../common/roles/enlarge-arp-table
    - role: repo_setup
    - role: capsule
    - role: capsule-location
    - role: puppet-autosign
...
