---
- hosts: container_hosts
  remote_user: root
  gather_facts: yes
  vars_files:
    - ../../conf/satperf.yaml
    - ../../conf/satperf.local.yaml
  roles:
    - role: repo_setup
      vars:
        additional_repos: "{{ containers_host_additional_repos }}"
    - role: client-scripts
...
