---
  # Systems ...-6048r....
  - shell: |
      for nic in ens3f1 enp5s0f1 $( ip a | grep '^[0-9]\+:' | sed 's/^[0-9]\+: \([^:]\+\):.*/\1/' | grep '\..*@' | cut -d '@' -f 1 ); do
        ip link set $nic down
        for addr in $( ip a show dev $nic scope global up | grep '^\s\+inet ' | sed 's/\s\+inet \([0-9.]\+\/[0-9]\+\) .*/\1/' ); do
          ip addr del $addr dev $nic
        done
        rm -rf /etc/sysconfig/network-scripts/ifcfg-$nic
        ip link delete dev $nic || true
      done
    when: "'-6048r.' in inventory_hostname"

  # Systems ...-r930....
  - shell: |
      for nic in em2 p1p1 p1p2 $( ip a | grep '^[0-9]\+:' | sed 's/^[0-9]\+: \([^:]\+\):.*/\1/' | grep '\..*@' | cut -d '@' -f 1 ); do
        ip link set $nic down
        for addr in $( ip a show dev $nic scope global up | grep '^\s\+inet ' | sed 's/\s\+inet \([0-9.]\+\/[0-9]\+\) .*/\1/' ); do
          ip addr del $addr dev $nic
        done
        rm -rf /etc/sysconfig/network-scripts/ifcfg-$nic
        ip link delete dev $nic || true
      done
    when: "'-r930.' in inventory_hostname"

  # Systems ...-r630....
  - shell: |
      for nic in p2p2 em2 em3 em4 $( ip a | grep '^[0-9]\+:' | sed 's/^[0-9]\+: \([^:]\+\):.*/\1/' | grep '\..*@' | cut -d '@' -f 1 ); do
        ip link set $nic down
        for addr in $( ip a show dev $nic scope global up | grep '^\s\+inet ' | sed 's/\s\+inet \([0-9.]\+\/[0-9]\+\) .*/\1/' ); do
          ip addr del $addr dev $nic
        done
        rm -rf /etc/sysconfig/network-scripts/ifcfg-$nic
        ip link delete dev $nic || true
      done
    when: "'-r630.' in inventory_hostname"

  # Systems ...-r620...
  - shell: |
      for nic in p2p4 em1 em2 $( ip a | grep '^[0-9]\+:' | sed 's/^[0-9]\+: \([^:]\+\):.*/\1/' | grep '\..*@' | cut -d '@' -f 1 ); do
        ip link set $nic down
        for addr in $( ip a show dev $nic scope global up | grep '^\s\+inet ' | sed 's/\s\+inet \([0-9.]\+\/[0-9]\+\) .*/\1/' ); do
          ip addr del $addr dev $nic
        done
        rm -rf /etc/sysconfig/network-scripts/ifcfg-$nic
        ip link delete dev $nic || true
      done
    when: "'-r620.' in inventory_hostname"

  # Systems ...-r730xd...
  #   em1 ... private
  #   em3 ... public
  - shell: |
      for nic in p4p1 p4p2 em2 em4 $( ip a | grep '^[0-9]\+:' | sed 's/^[0-9]\+: \([^:]\+\):.*/\1/' | grep '\..*@' | cut -d '@' -f 1 ); do
        ip link set $nic down
        for addr in $( ip a show dev $nic scope global up | grep '^\s\+inet ' | sed 's/\s\+inet \([0-9.]\+\/[0-9]\+\) .*/\1/' ); do
          ip addr del $addr dev $nic
        done
        rm -rf /etc/sysconfig/network-scripts/ifcfg-$nic
        ip link delete dev $nic || true
      done
    when: "'-r730xd.' in inventory_hostname"

  # Make sure 10G NIC have correct IP
  - lineinfile:
      dest: /etc/sysconfig/network-scripts/ifcfg-{{ nic_private }}
      regexp: "^ONBOOT="
      line: "ONBOOT=yes"
  - lineinfile:
      dest: /etc/sysconfig/network-scripts/ifcfg-{{ nic_private }}
      regexp: "^BOOTPROTO="
      line: "BOOTPROTO=static"
  - lineinfile:
      dest: /etc/sysconfig/network-scripts/ifcfg-{{ nic_private }}
      regexp: "^IPADDR="
      line: "IPADDR={{ ip }}"
  - lineinfile:
      dest: /etc/sysconfig/network-scripts/ifcfg-{{ nic_private }}
      regexp: "^NETMASK="
      line: "NETMASK=255.0.0.0"

  # Restart network
  - name: "Kill all dhclients (network service was not restarting)"
    command:
      killall dhclient
    ignore_errors: true
  - name: "Restart network"
    command:
      service network restart
...
