---
#
# Generic Playbook to install collectd on generic machine types, use tags to seperate machine type:
#
# ansible-playbook -i hosts install/collectd-generic.yml --tags="baremetal"
# ansible-playbook -i hosts install/collectd-generic.yml --tags="guest"
# ansible-playbook -i hosts install/collectd-generic.yml --tags="graphite"
# ansible-playbook -i hosts install/collectd-generic.yml --tags="satellite6"
# ansible-playbook -i hosts install/collectd-generic.yml --tags="baremetal,guest"

- hosts: graphite
  remote_user: root
  vars:
    config_type: graphite
  vars_files:
    - ../../conf/satperf.yaml
    - ../../conf/satperf.local.yaml
  roles:
    - collectd-generic
  tags: graphite

- hosts: satellite6
  remote_user: root
  vars:
    config_type: satellite6
  vars_files:
    - ../../conf/satperf.yaml
    - ../../conf/satperf.local.yaml
  roles:
    - collectd-generic
  tags: satellite6

- hosts: capsules
  remote_user: root
  vars:
    config_type: capsules
  vars_files:
    - ../../conf/satperf.yaml
    - ../../conf/satperf.local.yaml
  roles:
    - collectd-generic
  tags: capsules

- hosts: docker-hosts
  remote_user: root
  vars:
    config_type: docker-hosts
  vars_files:
    - ../../conf/satperf.yaml
    - ../../conf/satperf.local.yaml
  roles:
    - collectd-generic
  tags: docker-hosts
